language: python
env:
    - TOXENV=py27
    - TOXENV=py33
virtualenv:
  system_site_packages: true
before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sudo apt-get update
install:
 - sudo apt-get install open-cobol
 - sudo apt-get install python-qt4;
 - sudo apt-get install python3-pyqt4;
 - pip install --quiet --use-mirrors tox
script:
  - tox
